export default [
  {
    id: 1,
    title: "IOS Developer",
    company: "Apple",
    type: "Full Time",
    exp: "Fresher",
    location: "Hybrid",
    skills: ["SwiftUI", "Uikit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "Amazon",
    type: "Full Time",
    exp: "Fresher",
    location: "In-Office",
    skills: ["Javascript", "Nextjs", "Tailwind CSS"],
    job_link: "https://www.amazon.jobs/en/",
  },
  {
    id: 3,
    title: "Android Developer",
    type: "Part Time",
    location: "Remote",
    exp: "Senior Level",
    company: "Facebook",
    skills: ["Kotlin", "MVVM"],
    job_link: "https://facebook.com/careers",
  },
  {
    id: 4,
    title: "Developer Advocate",
    type: "Contract",
    location: "Hybrid",
    exp: "Junior Level",
    company: "Netflix",
    skills: ["web3", "Content Creation", "Community"],
    job_link: "https://jobs.netflix.com/",
  },
  {
    id: 5,
    title: "Quality Engineer",
    type: "Full Time",
    location: "Remote",
    exp: "Mid level",
    company: "Trellix",
    skills: ["Python", "selenium", "Gherkin"],
    job_link: "https://careers.trellix.com/",
  },
];
